public class calculator {

@AuraEnabled    
    public static Integer keypressed(String str, Integer i)
    {
        String[] nmbr;
switch on str
{
    when '1' {
    nmbr[i] = str;
    }
    
    when '2' {
    nmbr[i] = str;
    }
    
    when '3' {
    nmbr[i] = str;
    }
    
    when '4' {
    nmbr[i] = str;
    }
    
    when '5'{
    nmbr[i] = str;
    }
    
    when '6'{
    nmbr[i] = str;
    }
    
    when '7'{
    nmbr[i] = str;
    }
    
    when '8'{
    nmbr[i] = str;
    }
    
    when '9'{
    nmbr[i] = str;
    }
    
    when '0'{
    nmbr[i] = str;
    }

} 
        return 7;
    }

}